### PR TITLE
Add agda-lib file

### PR DESCRIPTION
**Pull request by vikraman**

### CODE REVIEW

**Comment by vikraman** [comment]
I don't know how the name ended up being `agda-prelude`!

**Comment by JacquesCarette** [comment]
I am not sure I had even noticed.  Hmm, what should it be changed to?

**Comment by vikraman** [comment]
It should be `categories` I think, sorry I probably copied it from the agda-prelude repository and forgot to change.

**Comment by JacquesCarette** [comment]
No problem - fixed and pushed.  BTW, I just got commit rights to copumpkin/categories.git, so I can start pushing some of those changes back to origin.

**Pull request merged**
